version: "3.9"
services:
  sentiment-client:
    build: .
    ports:
      - "5001:5000"
    networks:
      - custom-network

  sentiment-server:
    image: "mahsan/sentiment-server:latest"
    ports:
      - "8001:8000"
    networks:
      - custom-network
networks:
  custom-network:
    external: false